Django05/class04/class04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

Django05/class04/weather/urls.py
from django.urls import path
from weather import views

app_name = 'weather'

urlpatterns = [
    path('', views.index),
    path('detail/<int:city_id>/', views.detail, name='detail'),
]

Django05/class04/weather/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    

Django05/class04/weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name' : TextInput(attrs={'class' : 'input', 'placeholder' : '도시를 입력하세요.'}),
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        if City.objects.filter(name=name).exists():
            raise forms.ValidationError("이미 존재하는 도시입니다.")
        return name

Django05/class04/weather/views.py
from django.shortcuts import render, get_object_or_404
import requests
from .models import City
from .forms import CityForm

# Create your views here.
def index(request):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=API_KEY'
    
    cities = City.objects.all()

    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            form.save()
    
    form = CityForm()
    weather_data = []

    for city in cities:
        city_weather = requests.get(url.format(city)).json()

        weather = {
            'id' : city.id,
            'city' : city,
            'temperature' : round((city_weather['main']['temp']-32)*5/9, 1),
            'description' : city_weather['weather'][0]['description'],
            'icon' : city_weather['weather'][0]['icon'],
        }
        print(weather)
        weather_data.append(weather)

    context = {'weather_data' : weather_data, 'form' : form}

    return render(request, 'weather/index.html', context)

def detail(request, city_id) :
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=API_KEY'

    city = get_object_or_404(City, pk=city_id)
    city_weather = requests.get(url.format(city)).json()

    weather = {
        'id' : city.id,
        'city' : city,
        'temperature' : round((city_weather['main']['temp']-32)*5/9, 1),
        'description' : city_weather['weather'][0]['description'],
        'lon' : city_weather['coord']['lon'],
        'lat' : city_weather['coord']['lat'],
    }
  
    return render(request, 'weather/detail.html', {'weather':weather})

Django05/class04/weather/templates/weather/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>도시 상세 정보</title>
        <script src="https://maps.googleapis.com/maps/api/js?key=API_KEY"></script>

        <style>
            #map {
                height: 600px;
                width: 600px;
            }
        </style>
    </head>
    <body>
        <h1>{{weather.city}} 상세 정보</h1>
        <p>온도 : {{weather.temperature}}</p>
        <p>날씨 : {{weather.description}}</p>
        <p>위도 : {{weather.lat}}</p>
        <p>경도 : {{weather.lon}}</p>

        <div id="map"></div>

        <script type="text/javascript">
        window.initMap = function() {
            var lat = {{weather.lat}};
            var lon = {{weather.lon}};

            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: lat, lng: lon},
                zoom : 12
            });
        }

        initMap();
        </script>
    </body>
</html>

Django05/class04/weather/templates/weather/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>오늘의 날씨</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css"/>
    </head>
    <body>
        <section class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">오늘의 날씨</h1>
                </div>
            </div>
        </section>
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-4 is-4">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="field has-addons">
                                <div class="control is-expanded">
                                    {{form.name}}
                                </div>
                                <div class="control">
                                    <button class="button is-info">
                                        추가하기
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-4 is-4">
                        {% for weather in weather_data %}
                        <div class="box">
                            <a href="{% url 'weather:detail' weather.id %}">
                                <article class="media">
                                    <div class="media-left">
                                        <figure class="image is-50x50">
                                            <img src="http://openweathermap.org/img/w/{{weather.icon}}.png" alt="image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <p>
                                            <span class="title">{{weather.city}}</span>
                                            <br>
                                            <span class="subtitle">{{weather.temperature}}°C</span>
                                            <br> {{weather.description}}
                                        </p>
                                    </div>
                                </article>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>